
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReactQueryProvider } from "./components/providers/ReactQueryProvider";
import ProtectedRoute from "./components/providers/ProtectedRoute";
//import { ReduxProvider } from "./components/providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  {/* <ReduxProvider> */}
<ReactQueryProvider>
    <ProtectedRoute>
      {children}
      <Toaster position="top-center" reverseOrder={false} />
    </ProtectedRoute>
</ReactQueryProvider>
  {/* </ReduxProvider> */}

      </body>
    </html>
  );
}
